name: /Volumes/YNSHUNG/Coding/mynutriapps/mynutriapps-ai/.conda
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blinker=1.9.0=py311hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - click=8.1.7=py311hca03da5_0
  - flask=3.1.0=py311hca03da5_0
  - itsdangerous=2.2.0=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - markupsafe=3.0.2=py311h80987f9_0
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.16=h02f6b3c_0
  - pip=25.0=py311hca03da5_0
  - python=3.11.11=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=75.8.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - werkzeug=3.1.3=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - apscheduler==3.11.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.18.0
      - flask-apscheduler==1.13.1
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.4
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - thop==0.1.1-2209072238
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - ultralytics==8.1.34
      - urllib3==2.3.0
      - waitress==3.0.2
prefix: /Volumes/YNSHUNG/Coding/mynutriapps/mynutriapps-ai/.conda
